Add a small patch series to test webhook connection
tianocore/edk2-codereview pull request #1
Opened 2020-05-11 17:20 UTC by mdkinney

Add a small patch series with 5 commits that adds 5 files to the root of the repo.

This patch series is not intended to be merged.  It will be closed and abandoned later.

Signed-off-by: Michael D Kinney <michael.d.kinney@intel.com>

2020-05-11 18:19 UTC, bcran commented
Reviewed-by: Rebecca Cran <rebecca@bsdio.com>

Is there a limit on the size of patches that will be sent to the mailing list?

2020-05-11 18:54 UTC, mdkinney commented
I have tested a large number of patches in a patch series to make sure we do not have the groups.io limitations.

I have not tried a large single patch yet to see what the size limit is.  This would be a good unit test.

2020-05-11 22:52 UTC, lersek commented
Usability question:

assume I open the following link in a new browser window: `https://github.com/tianocore/edk2-codereview/commit/441a008424d031949547b4d6dfa851ef895c2d4d#comments` and leave a comment there. Further assume that I've closed all other browser windows and tabs.

How do I get back from that view to the containing pull request, in my browser?

Thanks.

2020-05-11 22:55 UTC, lersek commented
Another question:

I've provided feedback on all five patches, one by one. The banner at the top of this page still says my review is being requested. How do I make that go away? Thanks.

2020-05-11 22:56 UTC, lersek requested changes
... I guess I can say "please see my per-patch comments".
(and because some of those comments request a re-spin, I'll have to select the "request changes" radio button here)

2020-05-13 12:24 UTC, niruiyu commented
All

2020-05-14 02:41 UTC, niruiyu reviewed
Try inline comments.

2020-05-14 02:41 UTC, niruiyu commented on 5.txt
> +World
Check

2020-05-14 02:41 UTC, niruiyu commented on 5.txt
> +World
Ch

2020-05-14 02:41 UTC, niruiyu commented on 1.txt
> +World
Can it support embedded comments?

2021-06-17 03:19 UTC, closed without merging